import { Lead, User, KanbanColumn } from "@/types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Lucas Matheus",
    email: "Lucas@dev.com",
    role: "admin",
  },
  {
    id: "u2",
    name: "Maria Santos",
    email: "maria@otica.com.br",
    role: "vendedor",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "l1",
    nome: "João Costa",
    cidade: "São Paulo",
    email: "joao.costa@email.com",
    telefone: "11987654321",
    origem: "WhatsApp",
    conexao: "Alta",
    valor: 1500,
    dataCriacao: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Lucas Matheus",
    status: "Atendimento",
    observacoes: "Cliente interessado em armação premium",
  },
  {
    id: "l2",
    nome: "Ana Oliveira",
    cidade: "Rio de Janeiro",
    email: "ana.oliveira@email.com",
    telefone: "21987654322",
    origem: "Instagram",
    conexao: "Média",
    valor: 2500,
    dataCriacao: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Maria Santos",
    status: "Orçamento",
    observacoes: "Enviado orçamento para lentes progressivas",
  },
  {
    id: "l3",
    nome: "Carlos Mendes",
    cidade: "Belo Horizonte",
    email: "carlos.mendes@email.com",
    telefone: "31987654323",
    origem: "Google Ads",
    conexao: "Alta",
    valor: 3200,
    dataCriacao: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Lucas Matheus",
    status: "Fechado",
    observacoes: "Venda concluída - 2 armações",
  },
  {
    id: "l4",
    nome: "Mariana Souza",
    cidade: "Curitiba",
    email: "mariana.souza@email.com",
    telefone: "41987654324",
    origem: "Indicação",
    conexao: "Alta",
    valor: 1800,
    dataCriacao: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Maria Santos",
    status: "Novo",
    observacoes: "Indicação da cliente Ana",
  },
  {
    id: "l5",
    nome: "Roberto Lima",
    cidade: "Porto Alegre",
    email: "roberto.lima@email.com",
    telefone: "51987654325",
    origem: "Facebook",
    conexao: "Baixa",
    valor: 800,
    dataCriacao: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Lucas Matheus",
    status: "Perdido",
    observacoes: "Desistiu por preço",
  },
  {
    id: "l6",
    nome: "Fernanda Alves",
    cidade: "Brasília",
    email: "fernanda.alves@email.com",
    telefone: "61987654326",
    origem: "WhatsApp",
    conexao: "Média",
    valor: 1200,
    dataCriacao: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Maria Santos",
    status: "Remarketing",
    observacoes: "Retomar contato após 15 dias",
  },
  {
    id: "l7",
    nome: "Paulo Rodrigues",
    cidade: "Salvador",
    email: "paulo.rodrigues@email.com",
    telefone: "71987654327",
    origem: "Instagram",
    conexao: "Alta",
    valor: 2800,
    dataCriacao: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Lucas Matheus",
    status: "Atendimento",
    observacoes: "Necessita lentes para astigmatismo",
  },
  {
    id: "l8",
    nome: "Juliana Martins",
    cidade: "Fortaleza",
    email: "juliana.martins@email.com",
    telefone: "85987654328",
    origem: "Google Ads",
    conexao: "Média",
    valor: 1600,
    dataCriacao: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Maria Santos",
    status: "Fechado",
    observacoes: "Cliente satisfeito com atendimento",
  },
  {
    id: "l9",
    nome: "Ricardo Santos",
    cidade: "Recife",
    email: "ricardo.santos@email.com",
    telefone: "81987654329",
    origem: "Indicação",
    conexao: "Alta",
    valor: 2200,
    dataCriacao: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Lucas Matheus",
    status: "Orçamento",
    observacoes: "Aguardando aprovação do orçamento",
  },
  {
    id: "l10",
    nome: "Camila Ferreira",
    cidade: "Manaus",
    email: "camila.ferreira@email.com",
    telefone: "92987654330",
    origem: "Facebook",
    conexao: "Baixa",
    valor: 950,
    dataCriacao: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    responsavel: "Maria Santos",
    status: "Novo",
    observacoes: "Primeiro contato realizado",
  },
];

export const defaultKanbanColumns: KanbanColumn[] = [
  { id: "Novo", name: "Novo", color: "hsl(199, 89%, 48%)" },
  { id: "Atendimento", name: "Atendimento", color: "hsl(48, 96%, 53%)" },
  { id: "Orçamento", name: "Orçamento", color: "hsl(262, 52%, 47%)" },
  { id: "Fechado", name: "Fechado", color: "hsl(142, 71%, 45%)" },
  { id: "Perdido", name: "Perdido", color: "hsl(0, 84%, 60%)" },
  { id: "Remarketing", name: "Remarketing", color: "hsl(280, 65%, 60%)" },
];
